<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <xacro:macro name="front_camera" params="name">
    <xacro:property name="camera_thick" value="0.01"/>
    <xacro:property name="camera_side" value="0.01"/>

    <joint name="camera_joint" type="fixed">
        <parent link="top_cover"/>
        <child link="camera_link"/>
        <origin xyz="${cover_rad + camera_thick / 2} 0 0.0" rpy="0 0 0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_thick} ${camera_side} ${camera_side}"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>

    <gazebo reference="camera_link">
      <material>Gazebo/Red</material>
    </gazebo>

    <joint name="camera_optical_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0.005 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"></link>



    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>

        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>
  </xacro:macro>
</robot>

