<?xml version="1.0"?>
<robot>  

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <always_on>false</always_on>
      <legacy_mode>false</legacy_mode>
      <update_rate>20</update_rate>
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
      <torque>20</torque>
      <command_topic>/fl_robot_py/base_controller/cmd_vel2</command_topic>
      <odometry_topic>/fl_robot_py/base_controller/odom2</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>

   <!-- Add ROS plugin so we can interact with our robot -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>
  
   <gazebo reference="sensor_laser">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <visualize>false</visualize>
      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>181</samples>
            <resolution>1.000000</resolution>
            <min_angle>-1.57</min_angle>
            <max_angle>1.57</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>30.0</max>
          <resolution>0.015</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="scans" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan2</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>sensor_laser</frame_name>
      </plugin>
    </sensor>
  </gazebo>
  <gazebo reference="sensor_laser">
    <mu1>0.01</mu1>
    <mu2>0.01</mu2>
<!--    <material>Gazebo/Black</material> -->
  </gazebo>


</robot>

