<?xml version="1.0"?>
<robot name="mv_robot1" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- static>true</static-->
  <xacro:property name="base_width" value="0.16"/>
  <xacro:property name="base_len" value="0.16"/>
  <xacro:property name="base_thick" value="0.07"/>
  <xacro:property name="cover_rad" value="0.15"/>
  <xacro:property name="cover_thick" value="0.01"/>
  <xacro:property name="north_rad" value="0.01"/>
  
  
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="base_wheel_gap" value="0.007"/>
  <xacro:property name="wheel_separation" value="0.174"/> <!-- not used -->
  <xacro:property name="wheel_joint_offset" value="0.02"/>
    

  <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}"/>
  <xacro:property name="caster_wheel_mass" value="0.001"/>
  <xacro:property name="caster_wheel_joint_offset" value="0.052"/>

  <!--Gazebo Color Properties-->
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="top_cover">
<!--    <material>Gazebo/GreenTransparentOverlay</material> -->
    <material>Gazebo/Green</material>
  </gazebo>
  
  <gazebo reference="left_wheel">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Green</material>
  </gazebo>
  
  <gazebo reference="sensor_laser">
    <material>Gazebo/Gray</material>
  </gazebo>
  
  <gazebo reference="north">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="caster_wheel">
    <material>Gazebo/Blue</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
    <slip1>1.0</slip1>
    <slip2>1.0</slip2>
    <selfCollide>true</selfCollide>
    <gravity>true</gravity>
  </gazebo>
  
  
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  <material name="mycolor">
    <color rgba="0.1 0.2 0.2 1.0"/>
  </material>
  
  <!--Interial macros-->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
    </inertial>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0" izz="${2.0*m*(r*r)/5.0}"/>
    </inertial>
  </xacro:macro>

  <!--Base Footprint-->
  <link name="base_footprint">
<!--    <xacro:box_inertia m="10" w="0.001" h="0.001" d="0.001"/> -->
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <!--Base link-->
  <link name="base_link">
    <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="0.01"/>
    <visual>
      <geometry>
        <box size="${base_len} ${base_width} ${base_thick}"/>
      </geometry>
<!--      <material name="black"/> -->
    </visual>
    <collision>
      <geometry>
        <box size="${base_len} ${base_width} ${base_thick}"/>
      </geometry>
    </collision>
  </link>
  <link name="top_cover">
    <xacro:cylinder_inertia m="1" r="${cover_rad}" h="${cover_thick}"/>
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
        <cylinder radius="${cover_rad}" length="${cover_thick}" /> 
      </geometry>
<!--      <material name="mycolor" /> -->
    </visual>
    <collision name="cover_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${cover_rad}" length="${cover_thick}" />
      </geometry>
    </collision>
    <sensor name="my_contact" type="contact">
      <contact>
         <collision>cover_collision</collision>
       </contact>
     </sensor>

  </link>

  <link name="north">
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
        <cylinder radius="${north_rad}" length="0.001" /> 
      </geometry>
    </visual>
    <collision name="north_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.01" length="0.001" /> 
      </geometry>
    </collision>
  </link>
  <joint name="north_cover_joint" type="fixed">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="top_cover"/>
    <child link="north"/>
    <origin xyz=" ${cover_rad - north_rad} 0 ${cover_thick / 2}" rpy="0 0 0"/>
  </joint>
  
  <link name="south">
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
        <cylinder radius="${north_rad}" length="0.001" /> 
      </geometry>
    </visual>
    <collision name="north_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.01" length="0.001" /> 
      </geometry>
    </collision>
  </link>
  <joint name="south_cover_joint" type="fixed">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="top_cover"/>
    <child link="south"/>
    <origin xyz=" ${-cover_rad + north_rad} 0 ${cover_thick / 2}" rpy="0 0 0"/>
  </joint>
  
  <joint name="cover_base_joint" type="fixed">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="top_cover"/>
    <origin xyz=" 0 0 ${(base_thick + cover_thick) / 2}" rpy="0 0 0"/>
  </joint>
  
  
  <!--base_link to base_footprint Joint-->
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius + 0.005}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <!--Wheel link & joint macro-->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${reflect * pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.005"/>
        </geometry>
        <material name="white"/> 
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${reflect * pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.005"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>200.0</mu>
              <mu2>100.0</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="0.005"/>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${-wheel_joint_offset} ${((base_width/2)+base_wheel_gap)*reflect} -0.005" rpy="0 0 0"/>
    </joint>
    <transmission name="${prefix}_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_motor">
        <mechanicalReduction>0</mechanicalReduction>
      </actuator>
      <joint name="${prefix}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

  <!--Create Left & Right Wheel links/joints-->
  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>

  <!--Caster Wheel Link -->
  <link name="caster_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="1" r="${caster_wheel_radius}"/>
  </link>

  <!-- Caster Wheel Joint -->
	<joint name="fixed" type="fixed">
	  	<parent link="base_link"/>
	  	<child link="caster_wheel"/>
	</joint>


  <!-- laser  -->
  <xacro:property name="laser_size_x" value="0.03"/>
  <xacro:property name="laser_size_y" value="0.03"/>
  <xacro:property name="laser_size_z" value="0.04"/>
  <xacro:property name="laser_origin_x" value="0"/>
  <xacro:property name="laser_origin_y" value="0"/>
  <xacro:property name="laser_origin_z" value="${(cover_thick + laser_size_z)/ 2}"/>

  <link name="sensor_laser">
    <visual>
      <geometry>
        <cylinder radius="${laser_size_x / 2}" length="${laser_size_z}" />
      </geometry>
      <material name="blue"/>
    </visual> 
   <collision>
      <geometry>
        <cylinder radius="${laser_size_x / 2}" length="${laser_size_z}" />
        </geometry>
    </collision>
    <xacro:box_inertia m="0.2" w="${laser_size_x}" h="${laser_size_y}" d="${laser_size_z}"/>
  </link>

  <joint name="sensor_laser_joint" type="fixed">
    <origin xyz="${laser_origin_x} ${laser_origin_y} ${laser_origin_z}" rpy="0 0 0" />
    <parent link="top_cover"/>
    <child link="sensor_laser" />
  </joint>

 
  <xacro:include filename="$(find fl_robot_py)/urdf/fl_robot01_gazebo_plugins.xacro"/>

</robot>
